# model params
# resnet_v2_m_50
backbone_type: mbv3
loss_type: arcface
out_type: N

image_size: 112
embd_size: 512
class_num: 85742


# hyper params
bn_decay: 0.9
keep_prob: 0.4
weight_decay: !!float 5e-4
logits_scale: 64.0
logits_margin: 0.5
momentum: 0.9


# run params
val_bn_train: False
augment_flag: True
augment_margin: 16

gpu_num: 3
batch_size: 300
epoch_num: 20
step_per_epoch: 100000
val_freq: 2000

lr_steps: [40000, 60000, 80000]
#lr_steps: [18000, 38000, 58000] # start from 22000
lr_values: [0.004, 0.002, 0.0012, 0.0004]


# paths
pretrained_model: './output/20190522-005250/checkpoints/ckpt-m-22000'

train_data: ['/data/share/faces_ms1m_112x112/tf.tfrecord']
val_data: {'agedb_30': '/data/share/faces_ms1m_112x112/agedb_30.bin', 'lfw': '/data/share/faces_ms1m_112x112/lfw.bin', 'cfp_ff': '/data/share/faces_ms1m_112x112/cfp_ff.bin', 'cfp_fp': '/data/share/faces_ms1m_112x112/cfp_fp.bin', 'calfw': '/data/share/faces_ms1m_112x112/calfw.bin', 'cplfw': '/data/share/faces_ms1m_112x112/cplfw.bin', 'vgg2_fp': '/data/share/faces_ms1m_112x112/vgg2_fp.bin'}

output_dir: './output'

